import { Platform, StyleSheet } from 'react-native';

import { COLORS, SIZES } from '../../styles/theme';

const shadow = {
  ...Platform.select({
    ios: {
      shadowColor: '#7A6E87',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 18,
    },
    android: {
      elevation: 5,
    },
    default: {
      shadowColor: '#7A6E87',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 18,
    },
  }),
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FBF8FC',
  },
  content: {
    paddingHorizontal: SIZES.padding,
    paddingTop: 26,
    paddingBottom: 100,
  },
  eyebrow: {
    color: '#9B6800',
    fontSize: 11,
    fontWeight: '900',
  },
  pageTitle: {
    marginTop: 8,
    color: COLORS.primary,
    fontSize: 18,
    fontWeight: '900',
  },
  subtitle: {
    maxWidth: 310,
    marginTop: 8,
    color: '#6D6576',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '500',
  },
  summaryCard: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 25,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    paddingHorizontal: 20,
    ...shadow,
  },
  summaryIcon: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    borderRadius: 22,
    backgroundColor: '#FFE4A8',
  },
  summaryLabel: {
    color: '#8B8493',
    fontSize: 10,
    fontWeight: '900',
  },
  summaryValue: {
    marginTop: 4,
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '800',
  },
  filterBar: {
    height: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 24,
    marginBottom: 18,
    borderRadius: SIZES.radiusFull,
    backgroundColor: COLORS.white,
    padding: 6,
    ...shadow,
  },
  filterButton: {
    flex: 1,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: SIZES.radiusFull,
  },
  filterButtonActive: {
    backgroundColor: COLORS.primary,
  },
  filterText: {
    color: '#7B7185',
    fontSize: 10,
    fontWeight: '900',
  },
  filterTextActive: {
    color: COLORS.white,
  },
  loader: {
    marginVertical: 30,
  },
  emptyCard: {
    minHeight: 100,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    ...shadow,
  },
  emptyText: {
    marginTop: 8,
    color: '#7B7185',
    fontSize: 13,
    fontWeight: '700',
  },
  memberCard: {
    minHeight: 170,
    marginBottom: 18,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    padding: 18,
    ...shadow,
  },
  memberHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  avatarWrapper: {
    position: 'relative',
    width: 56,
    height: 56,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: COLORS.border,
  },
  avatarFallback: {
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: '#E7D1FF',
  },
  avatarInitials: {
    color: COLORS.primary,
    fontSize: 17,
    fontWeight: '900',
  },
  onlineDot: {
    position: 'absolute',
    right: -3,
    bottom: -3,
    width: 15,
    height: 15,
    borderWidth: 3,
    borderColor: COLORS.white,
    borderRadius: 8,
    backgroundColor: COLORS.secondary,
  },
  statusBadge: {
    borderRadius: SIZES.radiusFull,
    backgroundColor: '#F1E4FF',
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  statusBadgeInactive: {
    backgroundColor: '#ECE8EF',
  },
  statusText: {
    color: COLORS.primary,
    fontSize: 9,
    fontWeight: '900',
  },
  statusTextInactive: {
    color: '#746B7E',
  },
  memberName: {
    marginTop: 18,
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: '900',
  },
  memberRole: {
    marginTop: 3,
    color: '#655B70',
    fontSize: 13,
    fontWeight: '600',
  },
  memberFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 22,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  memberEmail: {
    flex: 1,
    marginLeft: 10,
    color: '#8B8493',
    fontSize: 12,
    fontWeight: '600',
  },
  formTitle: {
    color: COLORS.primary,
    fontSize: 18,
    fontWeight: '900',
  },
  inputLabel: {
    width: '100%',
    marginTop: 14,
    marginBottom: 7,
    color: '#6E637A',
    fontSize: 10,
    fontWeight: '900',
  },
  input: {
    width: '100%',
    minHeight: 47,
    borderRadius: 8,
    backgroundColor: '#F3EDF1',
    paddingHorizontal: 13,
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '600',
    borderWidth: 1,
    borderColor: '#E1D8DE',
  },
  passwordContainer: {
    width: '100%',
    minHeight: 47,
    borderRadius: 8,
    backgroundColor: '#F3EDF1',
    borderWidth: 1,
    borderColor: '#E1D8DE',
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 6,
  },
  passwordInput: {
    flex: 1,
    height: '100%',
    paddingHorizontal: 13,
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '600',
  },
  eyeButton: {
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButton: {
    width: '100%',
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 28,
    borderRadius: SIZES.radiusFull,
    backgroundColor: COLORS.primary,
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '900',
  },
  floatingButton: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 29,
    backgroundColor: COLORS.primary,
    ...shadow,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    alignItems: 'center',
    ...shadow,
  },
  modalHeader: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  closeModalButton: {
    padding: 4,
  },

  // ===============================================
  // ESTILOS: MODAL POP-UP DE OPÇÕES (3 PONTINHOS)
  // ===============================================
  optionsModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end', // Fica na base da tela
  },
  optionsModalContainer: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
  },
  optionsModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EAF2',
    paddingBottom: 15,
  },
  optionsModalTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.text,
    maxWidth: 250,
  },
  optionsModalSubtitle: {
    fontSize: 12,
    color: '#8B8493',
    marginTop: 2,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
  },
  optionIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3EDF1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  optionButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.text,
  },
  optionSeparator: {
    height: 1,
    backgroundColor: '#F0EAF2',
    marginVertical: 4,
  },
  cancelOptionButton: {
    marginTop: 20,
    backgroundColor: '#F3EDF1',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  cancelOptionText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#655B70',
  },
});