import { StyleSheet } from "react-native";
import { COLORS, SIZES } from "../../styles/theme";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
        padding: 25,
        paddingTop: 45,
    },
    title: {
        fontSize: SIZES.fontTitle,
        fontWeight: 'bold',
        color: COLORS.text,
    },
    boardadmin: {
        width: '100%',
        padding: 27,
        paddingLeft: 32,
        paddingRight: 32,
        borderRadius: 30,
        overflow: 'hidden',
        position: 'relative',
    },
    yellowGlow: {
        position: 'absolute',
        width: 215,
        height: 240,
        borderRadius: 999,
        backgroundColor: COLORS.secondary,
        top: -20,
        right: -30,
        opacity: 0.20,
        elevation: 20,
        shadowColor: COLORS.secondary,
        shadowOffset: {
            width: -50,
            height: -2,
        },
        shadowOpacity: 0.9,
        shadowRadius: 40,
    },
    type: {
        color: COLORS.white,
        fontSize: SIZES.fontSection,
        textTransform: 'uppercase',
        opacity: 0.9,
    },
    name: {
        color: COLORS.white,
        fontSize: SIZES.fontTitle,
        paddingTop: 10,
        paddingBottom: 10,
        fontWeight: 'bold',
    },
    text: {
        color: COLORS.white,
        fontSize: SIZES.fontText,
        opacity: 0.8
    },
    appointments: {
        width: '100%',
        backgroundColor: COLORS.container,
        padding: 32,
        borderRadius: 30,
        marginTop: 30,
    },
    popularservices: {
        backgroundColor: COLORS.container,
        padding: 30,
        paddingTop: 25,
        paddingBottom: 20,
        borderRadius: 30,
        marginTop: 30,
    },
    appointmentmonths: {
        backgroundColor: COLORS.container,
        padding: 30,
        paddingTop: 25,
        paddingBottom: 20,
        borderRadius: 30,
        marginTop: 30
    },
    totalinvoiceds: {
        backgroundColor: COLORS.container,
        padding: 30,
        paddingTop: 25,
        paddingBottom: 20,
        borderRadius: 30,
        marginTop: 30
    },
    titleSection: {
        fontSize: SIZES.fontSubsection,
        fontWeight: 'bold',
        color: COLORS.section,
    },
    numbers: {
        fontSize: SIZES.fontNumbers,
        fontWeight: 'bold',
        color: COLORS.section,
    },
    information: {
        fontSize: SIZES.fontSection,
        color: COLORS.titlesubsection,
        paddingTop: 5,
        paddingBottom: 20,
    },
    buttonAppointment: {
        backgroundColor: COLORS.primary,
        borderRadius: 30,
        width: 185,
        alignItems: 'center',
    },
    appointment:{
        backgroundColor: COLORS.white,
        borderRadius: 20,
        marginTop: 20,
        padding: 15,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    pet: {
        fontSize: SIZES.fontHeader,
        fontWeight: 'bold',
        color: COLORS.section,
    },
    service:{
        color: COLORS.titlesubsection,
    },
    hour: {
        color: COLORS.titlesubsection,
    },
    status: {
        width: '35%',
        color: COLORS.titlesubsection,
        fontSize: SIZES.fontStatus,
        textTransform: 'uppercase',
        fontWeight: 'bold',
        backgroundColor: COLORS.gray,
        textAlign: 'center',
        paddingVertical: 8,
        paddingHorizontal: 5,
        borderRadius: 20,
        overflow: 'hidden'
    },
    datappointment: {
        flex: 1,
        paddingHorizontal: 10,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    imagecontainer: {
        width: 45,
        height: 45,
        borderRadius: 15,
        overflow: 'hidden',
    },
    image: {
        width: '100%',
        height: '100%',
    },
    iconSection: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        width: 43,
        height: 45,
        padding: 5,
        borderRadius: 17,
        backgroundColor: COLORS.iconBackground,
    },
    iconStar: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        width: 43,
        height: 45,
        padding: 5,
        borderRadius: 17,
        backgroundColor: COLORS.iconStar
    },
    infoSection: {
        fontSize: SIZES.fontStatus,
        color: COLORS.titlesubsection,
        textTransform: 'uppercase',
        paddingTop: 25,
        paddingBottom: 5,  
    },
});